[package]
name = "cw-start"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = "1.2.7"
cosmwasm-std = "1.2.7"
thiserror = "1.0.40"
